#!/bin/sh

# Try to detect the service manager that is being used
if hash systemctl >/dev/null 2>&1; then
    # Make sure there's no already running session.
    if systemctl --user -q is-active mango.service; then
      echo 'A mango session is already running.'
      exit 1
    fi

    # Reset failed state of all user units.
    systemctl --user reset-failed

    # Import the login manager environment.
    systemctl --user import-environment

    # DBus activation environment is independent from systemd. While most of
    # dbus-activated services are already using `SystemdService` directive, some
    # still don't and thus we should set the dbus environment with a separate
    # command.
    if hash dbus-update-activation-environment 2>/dev/null; then
        dbus-update-activation-environment --all
    fi

    # Start mango and wait for it to terminate.
    systemctl --user --wait start mango.service
    # Force stop of graphical-session.target.
    systemctl --user start --job-mode=replace-irreversibly mango-shutdown.target
    # Unset environment that we've set.
    systemctl --user unset-environment WAYLAND_DISPLAY DISPLAY XDG_SESSION_TYPE XDG_CURRENT_DESKTOP
elif hash dinitctl >/dev/null 2>&1; then
    # Check that the user dinit daemon is running
    if ! pgrep -u "$(id -u)" dinit >/dev/null 2>&1; then
      echo "dinit user daemon is not running."
      exit 1
    fi

    # Make sure there's no already running session.
    if dinitctl --user is-started mango >/dev/null 2>&1; then
      echo 'A mango session is already running.'
      exit 1
    fi

    # Start mango
    dinitctl --user start mango
else
    echo "No systemd or dinit detected, please execute /usr/bin/mango"
fi
